name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "7 1 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TOTAL: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
